# Generated by Django 5.0.4 on 2024-05-31 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0004_cartdb_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdb',
            name='price',
        ),
    ]
